# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy

class gongpingjia_carinfo(scrapy.Item):
    geartype = scrapy.Field()
    makeyear = scrapy.Field()
    guideprice = scrapy.Field()
    emission = scrapy.Field()
    familyname_en = scrapy.Field()
    min_reg_year = scrapy.Field()
    saledesc = scrapy.Field()
    city_py = scrapy.Field()
    fmailylogo = scrapy.Field()
    brandname_en = scrapy.Field()
    city = scrapy.Field()
    familyname = scrapy.Field()
    max_reg_year = scrapy.Field()
    cityid = scrapy.Field()
    saledescid = scrapy.Field()
    factoryname = scrapy.Field()
    output = scrapy.Field()
    brandname = scrapy.Field()
    cityslug = scrapy.Field()
    url = scrapy.Field()
    grabtime = scrapy.Field()
    datasave = scrapy.Field()
    status = scrapy.Field()

class gongpingjia(scrapy.Item):
    geartype = scrapy.Field()
    makeyear = scrapy.Field()
    guideprice = scrapy.Field()
    emission = scrapy.Field()
    familyname_en = scrapy.Field()
    min_reg_year = scrapy.Field()
    mile = scrapy.Field()
    saledesc = scrapy.Field()
    city_py = scrapy.Field()
    fmailylogo = scrapy.Field()
    brandname_en = scrapy.Field()
    city = scrapy.Field()
    familyname = scrapy.Field()
    max_reg_year = scrapy.Field()
    cityid = scrapy.Field()
    saledescid = scrapy.Field()
    factoryname = scrapy.Field()
    output = scrapy.Field()
    brandname = scrapy.Field()
    url = scrapy.Field()
    grabtime = scrapy.Field()
    carinfo = scrapy.Field()
    carsource = scrapy.Field()
    price1_perfect = scrapy.Field()
    price2_perfect = scrapy.Field()
    price3_perfect = scrapy.Field()
    price4_perfect = scrapy.Field()
    price5_perfect = scrapy.Field()
    price6_perfect = scrapy.Field()
    price7_perfect = scrapy.Field()
    #
    price1_good = scrapy.Field()
    price2_good = scrapy.Field()
    price3_good = scrapy.Field()
    price4_good = scrapy.Field()
    price5_good = scrapy.Field()
    price6_good = scrapy.Field()
    price7_good = scrapy.Field()
    #
    price1_normal = scrapy.Field()
    price2_normal = scrapy.Field()
    price3_normal = scrapy.Field()
    price4_normal = scrapy.Field()
    price5_normal = scrapy.Field()
    price6_normal = scrapy.Field()
    price7_normal = scrapy.Field()
    status = scrapy.Field()

class jingzhungu_futureprice(scrapy.Item):
    mileage = scrapy.Field()
    makeyear = scrapy.Field()
    guideprice = scrapy.Field()
    brandname = scrapy.Field()
    familyid = scrapy.Field()
    brandid = scrapy.Field()
    remonth = scrapy.Field()
    provName = scrapy.Field()
    provID = scrapy.Field()
    salesdesc = scrapy.Field()

    familyname = scrapy.Field()
    cityName = scrapy.Field()
    salesdescid = scrapy.Field()
    cityID = scrapy.Field()
    factoryname = scrapy.Field()
    reyear = scrapy.Field()
    url = scrapy.Field()
    grabtime = scrapy.Field()

    month1 = scrapy.Field()
    month2 = scrapy.Field()
    month3 = scrapy.Field()
    month4 = scrapy.Field()
    month5 = scrapy.Field()
    year1 = scrapy.Field()
    year2 = scrapy.Field()
    year3 = scrapy.Field()
    year4 = scrapy.Field()
    year5 = scrapy.Field()
    status = scrapy.Field()


class jingzhungu(scrapy.Item):
    mileage = scrapy.Field()
    makeyear = scrapy.Field()
    guideprice = scrapy.Field()
    brandname = scrapy.Field()
    familyid = scrapy.Field()
    brandid = scrapy.Field()
    remonth = scrapy.Field()
    #provName = scrapy.Field()
    provID = scrapy.Field()
    salesdesc = scrapy.Field()
    source= scrapy.Field()
    fullname = scrapy.Field()

    familyname = scrapy.Field()
    #cityName = scrapy.Field()
    salesdescid = scrapy.Field()
    cityID = scrapy.Field()
    factoryname = scrapy.Field()
    reyear = scrapy.Field()
    url = scrapy.Field()
    grabtime = scrapy.Field()
    suggestGuidePrice_cs_normal = scrapy.Field()
    suggestGuidePrice_cs_good = scrapy.Field()
    suggestGuidePrice_cs_great = scrapy.Field()
    suggestGuidePrice_p_normal = scrapy.Field()
    suggestGuidePrice_p_good = scrapy.Field()
    suggestGuidePrice_p_great = scrapy.Field()
    status = scrapy.Field()

class che300_allproprice(scrapy.Item):
    geartype = scrapy.Field()
    provname = scrapy.Field()
    provid = scrapy.Field()
    makeyear = scrapy.Field()
    price = scrapy.Field()

    cityname = scrapy.Field()
    emission = scrapy.Field()
    reyear = scrapy.Field()
    month = scrapy.Field()
    price = scrapy.Field()

    factoryname = scrapy.Field()
    brandname = scrapy.Field()
    brandid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    date = scrapy.Field()
    salesdesc = scrapy.Field()
    milage = scrapy.Field()
    liter_type = scrapy.Field()
    salesdescid = scrapy.Field()
    max_reg_year = scrapy.Field()
    min_reg_year = scrapy.Field()
    url = scrapy.Field()
    grabtime = scrapy.Field()
    modelinfo = scrapy.Field()
    body_type = scrapy.Field()
    emission = scrapy.Field()
    doors = scrapy.Field()
    drive = scrapy.Field()
    engine_power = scrapy.Field()
    geartype = scrapy.Field()

    che300id = scrapy.Field()
    factoryname = scrapy.Field()
    market_date = scrapy.Field()
    guideprice = scrapy.Field()
    familyname = scrapy.Field()
    stopyear = scrapy.Field()
    makeyear = scrapy.Field()
    highlight_config = scrapy.Field()

    localprov = scrapy.Field()
    localprice = scrapy.Field()
    status = scrapy.Field()

class che300_futureprice(scrapy.Item):
    geartype = scrapy.Field()
    provname = scrapy.Field()
    provid = scrapy.Field()
    makeyear = scrapy.Field()
    price = scrapy.Field()
    cityname = scrapy.Field()
    cityid = scrapy.Field()
    emission = scrapy.Field()
    reyear = scrapy.Field()
    month = scrapy.Field()

    factoryname = scrapy.Field()
    brandname = scrapy.Field()
    brandid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    date = scrapy.Field()
    salesdesc = scrapy.Field()
    salesdescid = scrapy.Field()
    milage = scrapy.Field()
    liter_type = scrapy.Field()
    url = scrapy.Field()
    grabtime = scrapy.Field()

    register2017 = scrapy.Field()
    register2018 = scrapy.Field()
    register2019 = scrapy.Field()
    status = scrapy.Field()

class che300_historyprice(scrapy.Item):
    geartype = scrapy.Field()
    provname = scrapy.Field()
    provid = scrapy.Field()
    makeyear = scrapy.Field()
    price = scrapy.Field()
    cityname = scrapy.Field()
    cityid = scrapy.Field()
    emission = scrapy.Field()
    reyear = scrapy.Field()
    factoryname = scrapy.Field()
    brandname = scrapy.Field()
    brandid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    date = scrapy.Field()
    salesdesc = scrapy.Field()
    salesdescid = scrapy.Field()
    milage = scrapy.Field()
    liter_type = scrapy.Field()
    url = scrapy.Field()
    grabtime = scrapy.Field()
    price4 = scrapy.Field()

    price_h6 = scrapy.Field()
    price_h5 = scrapy.Field()
    price_h4 = scrapy.Field()
    price_h3 = scrapy.Field()
    price_h2 = scrapy.Field()
    price_h1 = scrapy.Field()
    status = scrapy.Field()


class che300modellist(scrapy.Item):
    geartype = scrapy.Field()
    provname = scrapy.Field()
    provid = scrapy.Field()
    makeyear = scrapy.Field()
    price = scrapy.Field()
    cityname = scrapy.Field()
    cityid=scrapy.Field()
    emission = scrapy.Field()
    factoryname = scrapy.Field()
    brandname = scrapy.Field()
    brandid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    salesdesc = scrapy.Field()
    salesdescid = scrapy.Field()
    liter =scrapy.Field()
    liter_type = scrapy.Field()
    min_reg_year =scrapy.Field()
    max_reg_year =scrapy.Field()

    url = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()


class che300_price(scrapy.Item):
    geartype = scrapy.Field()
    provname = scrapy.Field()
    provid = scrapy.Field()
    makeyear = scrapy.Field()
    price = scrapy.Field()
    cityname = scrapy.Field()
    cityid=scrapy.Field()
    emission = scrapy.Field()
    reyear = scrapy.Field()
    factoryname = scrapy.Field()
    brandname = scrapy.Field()
    brandid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    date = scrapy.Field()
    salesdesc = scrapy.Field()
    salesdescid = scrapy.Field()
    milage = scrapy.Field()
    liter_type = scrapy.Field()
    url = scrapy.Field()
    grabtime = scrapy.Field()
    situation = scrapy.Field()
    price1 = scrapy.Field()
    price2 = scrapy.Field()
    price3 = scrapy.Field()
    price4 = scrapy.Field()
    price5 = scrapy.Field()
    price6 = scrapy.Field()
    price7 = scrapy.Field()
    saleDateRange1 = scrapy.Field()
    saleDateRange2 = scrapy.Field()
    saleDateRange3 = scrapy.Field()
    saleDateRange4 = scrapy.Field()
    saleDateRange5 = scrapy.Field()
    saleDateRange6 = scrapy.Field()
    saleDateRange7 = scrapy.Field()
    saleRate1 = scrapy.Field()
    saleRate2 = scrapy.Field()
    saleRate3 = scrapy.Field()
    saleRate4 = scrapy.Field()
    saleRate5 = scrapy.Field()
    saleRate6 = scrapy.Field()
    saleRate7 = scrapy.Field()
    status = scrapy.Field()
    datasave = scrapy.Field()
    default = scrapy.Field()
    excellent = scrapy.Field()
    good =scrapy.Field()
    normal =scrapy.Field()
    data = scrapy.Field()
    year_2017 = scrapy.Field()
    year_2018 = scrapy.Field()
    year_2019 = scrapy.Field()
    year_2020 = scrapy.Field()
    year_2021 = scrapy.Field()
    dealer_price= scrapy.Field()
    individual_price= scrapy.Field()
    help_sold_price= scrapy.Field()
    dealer_buy_price= scrapy.Field()
    dealer_auction_price= scrapy.Field()
    dealer_low_buy_price= scrapy.Field()
    dealer_low_auction_price= scrapy.Field()
    individual_low_sold_price= scrapy.Field()
    dealer_low_sold_price= scrapy.Field()
    dealer_high_sold_price= scrapy.Field()
    low_help_sold_price= scrapy.Field()
    b2c_price = scrapy.Field()

class che300(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    id = scrapy.Field()
    salesdesc = scrapy.Field()
    datasave = scrapy.Field()
    status = scrapy.Field()
    geartype = scrapy.Field()
    provname = scrapy.Field()
    provid = scrapy.Field()
    makeyear = scrapy.Field()
    price = scrapy.Field()
    cityname = scrapy.Field()
    cityid = scrapy.Field()
    emission = scrapy.Field()
    factoryname = scrapy.Field()
    brandname = scrapy.Field()
    brandid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    salesdesc = scrapy.Field()
    salesdescid = scrapy.Field()
    liter = scrapy.Field()
    liter_type = scrapy.Field()
    min_reg_year = scrapy.Field()
    max_reg_year = scrapy.Field()

class che168citys(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    provname = scrapy.Field()
    provid = scrapy.Field()
    cityname = scrapy.Field()
    cityid = scrapy.Field()
    status = scrapy.Field()

class che168_price(scrapy.Item):
    provid = scrapy.Field()
    cityid = scrapy.Field()
    autohomeid = scrapy.Field()
    url = scrapy.Field()
    grabtime = scrapy.Field()
    price_range = scrapy.Field()
    price__low = scrapy.Field()
    price_hig = scrapy.Field()
    price_mid = scrapy.Field()
    guideprice = scrapy.Field()
    status = scrapy.Field()
    regDate = scrapy.Field()
    milage = scrapy.Field()
    type = scrapy.Field()


class che300TrendItem(scrapy.Item):
    url = scrapy.Field()
    status = scrapy.Field()
    grabtime = scrapy.Field()
    date201807 = scrapy.Field()
    date201810 = scrapy.Field()
    date201901 = scrapy.Field()
    date201904 = scrapy.Field()
    date201907 = scrapy.Field()
    date201910 = scrapy.Field()
    model = scrapy.Field()
    month = scrapy.Field()
    year = scrapy.Field()
    price = scrapy.Field()

class che300HistoryItem(scrapy.Item):
    url = scrapy.Field()
    status = scrapy.Field()
    grabtime = scrapy.Field()
    date201807 = scrapy.Field()
    date201806 = scrapy.Field()
    date201805 = scrapy.Field()
    date201804 = scrapy.Field()
    date201803 = scrapy.Field()
    date201802 = scrapy.Field()
    model = scrapy.Field()
    # month = scrapy.Field()
    year = scrapy.Field()
    price = scrapy.Field()
class Che300(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    grabtime = scrapy.Field()
    url = scrapy.Field()
    price1 = scrapy.Field()
    price2 = scrapy.Field()
    price3 = scrapy.Field()
    price4 = scrapy.Field()
    price5 = scrapy.Field()
    price6 = scrapy.Field()
    price7 = scrapy.Field()
    brand = scrapy.Field()
    series = scrapy.Field()
    salesdescid = scrapy.Field()
    regDate = scrapy.Field()
    cityid = scrapy.Field()
    prov = scrapy.Field()
    mile = scrapy.Field()

    status = scrapy.Field()